services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: auction_db
      POSTGRES_USER: test_db
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: