export const ChatRealtimeEventType = Object.freeze({
  NEW_MESSAGE: 'NEW_MESSAGE',
  CONVERSATION_UPDATED: 'CONVERSATION_UPDATED',
  UNREAD_UPDATED: 'UNREAD_UPDATED',
  MESSAGES_READ: 'MESSAGES_READ',
  USER_PRESENCE_UPDATED: 'USER_PRESENCE_UPDATED',
})
